import type { Creator } from './creator.types.js';

/** Seed data cho môi trường dev/test — chỉ creator ở trạng thái verified mới hiển thị công khai. */
export const CREATOR_SEED: readonly Creator[] = [
  {
    id: 'crt_0001',
    userId: null,
    displayName: 'Lan Chi Foodie',
    avatarUrl: null,
    bio: 'Food reviewer Hà Nội, chuyên quán café và street food. Video review chân thực, lên xu hướng đều.',
    city: 'Hà Nội',
    niches: ['f&b', 'cafe', 'street-food'],
    language: 'vi',
    creatorType: 'koc',
    status: 'verified',
    statusReason: null,
    socialAccounts: [
      {
        platform: 'tiktok',
        handle: '@lanchifoodie',
        url: 'https://www.tiktok.com/@lanchifoodie',
        followerCount: 48_000,
        isVerified: true,
      },
    ],
    audienceMetrics: null,
    serviceMode: 'both',
    availability: { availableDays: [], isPaused: false },
    portfolioItems: [],
    priceFromVnd: 1_500_000,
    rating: 4.8,
    completedBookings: 32,
    createdAt: '2026-05-02T08:00:00.000Z',
  },
  {
    id: 'crt_0002',
    userId: null,
    displayName: 'Minh Thu UGC',
    avatarUrl: null,
    bio: 'UGC creator chuyên quay dựng video sản phẩm cho local brand thời trang và mỹ phẩm.',
    city: 'Hồ Chí Minh',
    niches: ['fashion', 'beauty', 'ugc-video'],
    language: 'vi',
    creatorType: 'ugc',
    status: 'verified',
    statusReason: null,
    socialAccounts: [
      {
        platform: 'instagram',
        handle: '@minhthu.ugc',
        url: 'https://www.instagram.com/minhthu.ugc',
        followerCount: 12_500,
        isVerified: false,
      },
      {
        platform: 'tiktok',
        handle: '@minhthuugc',
        url: 'https://www.tiktok.com/@minhthuugc',
        followerCount: 8_900,
        isVerified: false,
      },
    ],
    audienceMetrics: null,
    serviceMode: 'both',
    availability: { availableDays: [], isPaused: false },
    portfolioItems: [],
    priceFromVnd: 900_000,
    rating: 4.6,
    completedBookings: 21,
    createdAt: '2026-05-20T08:00:00.000Z',
  },
  {
    id: 'crt_0003',
    userId: null,
    displayName: 'Hoàng Nam Lifestyle',
    avatarUrl: null,
    bio: 'Lifestyle influencer, nội dung khám phá quán mới và trải nghiệm dịch vụ tại Hà Nội.',
    city: 'Hà Nội',
    niches: ['lifestyle', 'f&b', 'travel'],
    language: 'vi',
    creatorType: 'influencer',
    status: 'verified',
    statusReason: null,
    socialAccounts: [
      {
        platform: 'youtube',
        handle: 'HoangNamLifestyle',
        url: 'https://www.youtube.com/@HoangNamLifestyle',
        followerCount: 105_000,
        isVerified: true,
      },
    ],
    audienceMetrics: null,
    serviceMode: 'both',
    availability: { availableDays: [], isPaused: false },
    portfolioItems: [],
    priceFromVnd: 5_000_000,
    rating: 4.9,
    completedBookings: 54,
    createdAt: '2026-04-15T08:00:00.000Z',
  },
  {
    id: 'crt_0004',
    userId: null,
    displayName: 'Bé Na Review',
    avatarUrl: null,
    bio: 'Nano creator mảng mẹ và bé, đồ gia dụng. Nội dung gần gũi, tương tác cao.',
    city: 'Đà Nẵng',
    niches: ['mom-baby', 'home'],
    language: 'vi',
    creatorType: 'koc',
    status: 'verified',
    statusReason: null,
    socialAccounts: [
      {
        platform: 'facebook',
        handle: 'benareview',
        url: 'https://www.facebook.com/benareview',
        followerCount: 22_000,
        isVerified: false,
      },
    ],
    audienceMetrics: null,
    serviceMode: 'both',
    availability: { availableDays: [], isPaused: false },
    portfolioItems: [],
    priceFromVnd: 700_000,
    rating: 4.4,
    completedBookings: 11,
    createdAt: '2026-06-10T08:00:00.000Z',
  },
  {
    id: 'crt_0005',
    userId: null,
    displayName: 'Quang Duy Tech',
    avatarUrl: null,
    bio: 'Reviewer đồ công nghệ và phụ kiện. Hồ sơ đang chờ duyệt.',
    city: 'Hồ Chí Minh',
    niches: ['tech'],
    language: 'vi',
    creatorType: 'influencer',
    status: 'pending_review',
    statusReason: null,
    socialAccounts: [
      {
        platform: 'tiktok',
        handle: '@quangduytech',
        url: 'https://www.tiktok.com/@quangduytech',
        followerCount: 67_000,
        isVerified: false,
      },
    ],
    audienceMetrics: null,
    serviceMode: 'both',
    availability: { availableDays: [], isPaused: false },
    portfolioItems: [],
    priceFromVnd: 3_000_000,
    rating: 0,
    completedBookings: 0,
    createdAt: '2026-07-01T08:00:00.000Z',
  },
  {
    // Hồ sơ demo của creator@demo.vn (usr_demo_creator) — trạng thái DRAFT để
    // chủ tài khoản demo tự hoàn thiện hồ sơ qua onboarding (CRE-001, CRE-007).
    id: 'crt_demo',
    userId: 'usr_demo_creator',
    displayName: 'Creator Demo',
    avatarUrl: null,
    bio: 'Creator demo chuyên review quán ăn và trải nghiệm dịch vụ địa phương. Nội dung chân thực, sẵn sàng nhận booking thử nghiệm.',
    city: 'Hà Nội',
    niches: ['f&b', 'lifestyle', 'travel'],
    language: 'vi',
    creatorType: 'koc',
    status: 'draft',
    statusReason: null,
    socialAccounts: [
      {
        platform: 'tiktok',
        handle: '@creatordemo',
        url: 'https://www.tiktok.com/@creatordemo',
        followerCount: 15_000,
        isVerified: false,
      },
    ],
    audienceMetrics: null,
    serviceMode: 'both',
    availability: { availableDays: ['mon', 'wed', 'fri', 'sun'], isPaused: false },
    portfolioItems: [],
    priceFromVnd: 1_000_000,
    rating: 0,
    completedBookings: 0,
    createdAt: '2026-08-04T08:00:00.000Z',
  },
];
